'use strict'

// MCGalaxy's shortcuts and aliases, so people coming from MCGalaxy can keep typing what they are used to.
// An entry with a space carries arguments: 'zadd add' makes /zadd x the same as /zone add x.
// They are added when the command registers; a real command name always wins over an alias.
module.exports = {
  // chat and info
  adminchat: ['admin'],
  opchat: ['op'],
  clear: ['playercls', 'globalcls all', 'gcls all'],
  about: ['whodid'],
  blocks: ['materials'],
  help: ['cmdhelp'],
  mapinfo: ['mi', 'winfo', 'worldinfo'],
  serverinfo: ['sinfo', 'host', 'zall'],
  time: ['ti'],
  top: ['most'],
  whois: ['whowas', 'info', 'i'],
  players: ['who'],
  pclients: ['clients'],
  levels: ['worlds', 'maps', 'loaded'],
  lastcmd: ['last'],
  rankinfo: ['ri'],
  whonick: ['realname'],
  bans: ['banned'],
  vote: ['vo'],
  alts: ['clones', 'whoip'],
  // essentials
  hold: ['holdthis'],
  reach: ['reachdistance'],
  entityrot: ['entrot'],
  tp: ['move', 'teleport'],
  tphere: ['summon', 's', 'fetch', 'bring'],
  tpa: ['tpaccept accept', 'tpdeny deny'],
  bot: ['botlist list'],
  // economy and games
  buy: ['purchase'],
  give: ['gib'],
  shop: ['store', 'item'],
  explode: ['ex'],
  // moderation
  ban: ['tempban', 'tb', 'kickban', 'kb'],
  banedit: ['be'],
  banip: ['bi', 'ipban'],
  unbanip: ['unipban'],
  xban: ['banx'],
  kick: ['k'],
  freeze: ['fz'],
  rank: ['setrank'],
  moveall: ['ma'],
  playeredit: ['pe', 'setinfo'],
  report: ['reports list'],
  undoplayer: ['xundo'],
  whitelist: ['wl'],
  // levels
  copylvl: ['wcopy', 'worldcopy'],
  deletelvl: ['wdelete', 'worlddelete', 'wremove'],
  fixgrass: ['fg'],
  load: ['mapload', 'wload'],
  lockdown: ['ld', 'wlock', 'wunlock'],
  main: ['h', 'wmain', 'worldmain'],
  newlvl: ['gen'],
  reload: ['reveal', 'rejoin', 'rd', 'wflush', 'worldflush'],
  renamelvl: ['wrename', 'worldrename'],
  resizelvl: ['wresize', 'worldresize'],
  save: ['mapsave', 'wsave', 'worldsave'],
  map: ['perbuild buildrank', 'wbuild buildrank', 'worldbuild buildrank', 'pervisit visitrank', 'waccess visitrank', 'worldaccess visitrank'],
  zone: ['zadd add', 'zremove delete', 'zdelete delete', 'zonelist list', 'zonetest check', 'ztest check'],
  // building
  cuboid: ['cw wire', 'ch hollow', 'walls walls', 'hbox hollow'],
  sphere: ['sph hollow', 'sphereh hollow'],
  spheroid: ['eh hollow'],
  fill: ['f3d 3d', 'fill3d 3d', 'f2d layer', 'fill2d layer'],
  line: ['ln'],
  mark: ['click', 'x'],
  measure: ['ms'],
  calculate: ['calc'],
  center: ['centre'],
  paint: ['p'],
  paste: ['v'],
  place: ['pl'],
  mirror: ['flip'],
  spin: ['rotate'],
  portal: ['o'],
  torus: ['tor', 'bagel'],
  write: ['wrt', 'writetext'],
  abort: ['a'],
  replacenot: ['rn'],
  triangle: ['tri'],
  static: ['t'],
  delete: ['d'],
  bind: ['cmdbind', 'cb']
}
